#!/usr/bin/env python3
"""
Generate the hints seed migration from "Entertain - Hints (seed).md".

The markdown file (repo root) is the source of truth for hint content. This
script parses its two tables (Benvinguda + Tips) and emits the idempotent seed
SQL — hint rows + their ca/es/en `translations` — mirroring the house seed
pattern (insert ... on conflict do nothing, then translations with where-not-
exists, joined on the natural `key`). Run it whenever the seed file changes:

    python3 tools/gen_hints_seed.py

Output: supabase/migrations/20260629000100_hints_seed.sql (overwritten).
Paths resolve relative to the repo, so it runs from any CWD. Pure stdlib.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "Entertain - Hints (seed).md")
OUT = os.path.join(REPO, "supabase", "migrations", "20260629000100_hints_seed.sql")


def parse(md_path):
    """Return [(key, kind, ca, es, en), ...] in file order."""
    rows = []
    with open(md_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("|"):
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) != 5:
                continue
            key, kind, ca, es, en = cells
            if key == "key" or set(key) <= {"-"}:  # header / separator row
                continue
            if kind not in ("welcome", "tip"):
                continue
            rows.append((key, kind, ca, es, en))
    return rows


def q(s):
    """SQL single-quoted literal with apostrophes doubled."""
    return "'" + s.replace("'", "''") + "'"


def main():
    rows = parse(SRC)
    welcome = sum(1 for r in rows if r[1] == "welcome")
    tips = sum(1 for r in rows if r[1] == "tip")

    hint_values = ",\n".join(f"  ({q(k)}, {q(kind)})" for k, kind, *_ in rows)

    tr_lines = []
    for key, _kind, ca, es, en in rows:
        tr_lines.append(f"  ({q(key)}, 'ca', {q(ca)})")
        tr_lines.append(f"  ({q(key)}, 'es', {q(es)})")
        tr_lines.append(f"  ({q(key)}, 'en', {q(en)})")
    tr_values = ",\n".join(tr_lines)

    sql = f"""-- Spec 026 Part A — hints seed (rows + ca/es/en translations).
-- GENERATED by tools/gen_hints_seed.py from "Entertain - Hints (seed).md".
-- Do not edit by hand; re-run the generator and commit. After seeding, hints are
-- edited directly in the DB (insert/update/delete a row + its translations) — no
-- app rebuild needed. {welcome} welcome + {tips} tips. Idempotent.

insert into public.hints (key, kind) values
{hint_values}
on conflict (key) do nothing;

insert into public.translations (entity_type, entity_id, locale, field, text)
select 'hint'::public.translation_entity_type,
       h.id,
       t.locale::public.profile_locale,
       'text',
       t.text
from public.hints h
join (values
{tr_values}
) as t(key, locale, text) on t.key = h.key
where not exists (
  select 1
  from public.translations existing
  where existing.entity_type = 'hint'::public.translation_entity_type
    and existing.entity_id = h.id
    and existing.locale = t.locale::public.profile_locale
    and existing.field = 'text'
);
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(sql)
    print(f"wrote: {OUT}  ({welcome} welcome + {tips} tips, {len(rows) * 3} translation rows)")


if __name__ == "__main__":
    main()
