#!/usr/bin/env python3
"""
Generate the hints SYNC migration (Spec 027 §9(b)).

The seed migration (20260629000100_hints_seed.sql) is already applied, so the
live DB still holds the original 44 hints. The source file "Entertain - Hints
(seed).md" is now at 40 (4 keys retired, 4 rewritten). Migrations run once, so
editing the seed would not touch the live DB — this emits a forward migration
that brings the DB in line with the source:

  1. Delete the 4 retired keys AND their translations. There is no
     delete-translations trigger on `hints` (the Spec 026 trigger only covers
     ingredient/dish/drink), so the translation rows are removed explicitly,
     before the hint rows.
  2. Update the ca/es/en text of the 4 rewritten keys to match the source file
     (only where it actually changed → idempotent).

Run whenever the retired/rewritten sets or their text change:

    python3 tools/gen_hints_sync.py

Output: supabase/migrations/20260630000000_hints_sync.sql (overwritten).
Paths resolve relative to the repo, so it runs from any CWD. Pure stdlib.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "Entertain - Hints (seed).md")
OUT = os.path.join(REPO, "supabase", "migrations", "20260630000000_hints_sync.sql")

# Keys dropped from the source file since the seed was generated.
RETIRED = ("menu_add_button", "hints_toggle", "event_status", "photos_pexels")
# Keys whose ca/es/en text was rewritten in the source file.
REWRITTEN = ("photos_three", "event_format", "config_suggestions", "menu_adhoc")


def parse(md_path):
    """Return {key: (ca, es, en)} for every data row in the source file."""
    out = {}
    with open(md_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line.startswith("|"):
                continue
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) != 5:
                continue
            key, kind, ca, es, en = cells
            if key == "key" or set(key) <= {"-"}:  # header / separator row
                continue
            if kind not in ("welcome", "tip"):
                continue
            out[key] = (ca, es, en)
    return out


def q(s):
    """SQL single-quoted literal with apostrophes doubled."""
    return "'" + s.replace("'", "''") + "'"


def main():
    rows = parse(SRC)
    missing = [k for k in REWRITTEN if k not in rows]
    if missing:
        raise SystemExit(f"rewritten keys absent from source: {missing}")

    retired_list = ",".join(q(k) for k in RETIRED)

    upd_lines = []
    for key in REWRITTEN:
        ca, es, en = rows[key]
        upd_lines.append(f"  ({q(key)}, 'ca', {q(ca)})")
        upd_lines.append(f"  ({q(key)}, 'es', {q(es)})")
        upd_lines.append(f"  ({q(key)}, 'en', {q(en)})")
    upd_values = ",\n".join(upd_lines)

    sql = f"""-- Spec 027 §9(b) — sync the hints DB to "Entertain - Hints (seed).md" (40 hints).
-- GENERATED by tools/gen_hints_sync.py. Do not edit by hand; re-run the generator.
-- The seed migration (…000100) is already applied (44 hints in the DB); this forward
-- migration trims the {len(RETIRED)} retired keys and rewrites {len(REWRITTEN)} others. Idempotent.

-- 1) Retired keys: delete their translations FIRST (no delete-translations trigger
--    covers kind='hint' — the Spec 026 trigger is only on ingredient/dish/drink),
--    then the hint rows.
delete from public.translations
 where entity_type = 'hint'::public.translation_entity_type
   and entity_id in (
     select id from public.hints where key in ({retired_list}));

delete from public.hints
 where key in ({retired_list});

-- 2) Rewritten keys: update ca/es/en text, only where it actually changed.
update public.translations t
   set text = v.text, updated_at = now()
  from public.hints h
  join (values
{upd_values}
  ) as v(key, locale, text) on v.key = h.key
 where t.entity_type = 'hint'::public.translation_entity_type
   and t.entity_id = h.id
   and t.locale = v.locale::public.profile_locale
   and t.field = 'text'
   and t.text is distinct from v.text;
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(sql)
    print(f"wrote: {OUT}  ({len(RETIRED)} retired, {len(REWRITTEN)} rewritten)")


if __name__ == "__main__":
    main()
