-- Spec 027 §9(b) — sync the hints DB to "Entertain - Hints (seed).md" (40 hints).
-- GENERATED by tools/gen_hints_sync.py. Do not edit by hand; re-run the generator.
-- The seed migration (…000100) is already applied (44 hints in the DB); this forward
-- migration trims the 4 retired keys and rewrites 4 others. Idempotent.

-- 1) Retired keys: delete their translations FIRST (no delete-translations trigger
--    covers kind='hint' — the Spec 026 trigger is only on ingredient/dish/drink),
--    then the hint rows.
delete from public.translations
 where entity_type = 'hint'::public.translation_entity_type
   and entity_id in (
     select id from public.hints where key in ('menu_add_button','hints_toggle','event_status','photos_pexels'));

delete from public.hints
 where key in ('menu_add_button','hints_toggle','event_status','photos_pexels');

-- 2) Rewritten keys: update ca/es/en text, only where it actually changed.
update public.translations t
   set text = v.text, updated_at = now()
  from public.hints h
  join (values
  ('photos_three', 'ca', 'Sabies que pots posar foto als plats, begudes i ingredients? Fes-la amb la càmera, tria''n una de la galeria, o cerca''n una en una col·lecció en línia.'),
  ('photos_three', 'es', '¿Sabías que puedes poner foto a platos, bebidas e ingredientes? Hazla con la cámara, elige una de la galería, o busca una en una colección en línea.'),
  ('photos_three', 'en', 'Did you know you can add a photo to dishes, drinks and ingredients? Take one with the camera, pick one from the gallery, or search an online collection.'),
  ('event_format', 'ca', 'Sabies que el format de l''esdeveniment ajusta les quantitats? En un àpat assegut cada plat es calcula per comensal; en un bufet es manté la ració del catàleg.'),
  ('event_format', 'es', '¿Sabías que el formato del evento ajusta las cantidades? En una comida sentada cada plato se calcula por comensal; en un bufé se mantiene la ración del catálogo.'),
  ('event_format', 'en', 'Did you know the event format adjusts quantities? At a seated meal each dish is calculated per guest; at a buffet the catalog serving is kept.'),
  ('config_suggestions', 'ca', 'Sabies que pots enviar-nos suggeriments des de Configuració?'),
  ('config_suggestions', 'es', '¿Sabías que puedes enviarnos sugerencias desde Configuración?'),
  ('config_suggestions', 'en', 'Did you know you can send us suggestions from Settings?'),
  ('menu_adhoc', 'ca', 'Sabies que pots afegir un ingredient extra a un plat dins un esdeveniment, i desar-lo a la recepta si vols que hi quedi per sempre?'),
  ('menu_adhoc', 'es', '¿Sabías que puedes añadir un ingrediente extra a un plato dentro de un evento, y guardarlo en la receta si quieres que quede para siempre?'),
  ('menu_adhoc', 'en', 'Did you know you can add an extra ingredient to a dish within an event, and save it to the recipe if you want it to stay for good?')
  ) as v(key, locale, text) on v.key = h.key
 where t.entity_type = 'hint'::public.translation_entity_type
   and t.entity_id = h.id
   and t.locale = v.locale::public.profile_locale
   and t.field = 'text'
   and t.text is distinct from v.text;
